### ISSUE TITLE
 Error: Connection refused

### ISSUE THREAD

**Issue by arunrajput220** [FIWARE/tutorials.IoT-over-MQTT#23]
I am getting  this error "**Error: Connection refused**" while running below command

docker run -it --rm --name mqtt-subscriber   --network fiware_default efrecon/mqtt-client sub -h mosquitto -t "/#"
Error: Connection refused

**Comment by jason-fox** [comment]
That is a nice little breaking change coming from Mosquitto 2.0. Commit  fc52921 now fixes the `docker-compose` to a fixed **1.6.14** release as shown:

```diff
  mosquitto:
-    image: eclipse-mosquitto
+    image: eclipse-mosquitto:1.6.14
```

You can make the change yourself or just pull the latest changes.

The `latest` version of [Mosquitto 2.0](https://mosquitto.org/documentation/migrating-to-2-0/) runs more securely by default and isn't letting in access from an unconfigured I.P. Since security is not the focus of the tutorial it is easily fixed by pinning to the older Mosquitto version.
